### ISSUE TITLE
Specification of UMD Global Name

### ISSUE THREAD

**Issue by gz65555** [oasis-engine/create-oasis-app#3]
We need a specification of global name in oasis library.

Oasis Engine use a [toGlobalName](https://github.com/oasis-engine/engine/blob/6a3706dbe78a4a9cdfff574adbe6f977f9eda9f2/rollup.config.js#L31) function to associate `package.json`'s name and global name.

For example. `oasis-engine` will be `oasisEngine` and `@oasis-engine/controls` will be `@oasisEngine/controls`.

Should library follow the specification of Oasis Engine?

**Comment by gz65555** [comment]
- `react` is `React`.
- `vue` is `Vue`

**Comment by eyworldwide** [comment]
`@oasisEngine/controls` is ugly and not friendly as a javascript variable. I think `oasisControls` maybe better.

**Comment by gz65555** [comment]
Using modern develogment of JavaScript won't have this confusion. There is a rule for ensure the only globle name for a package.
