### ISSUE TITLE
Opt template

### ISSUE THREAD

**Issue by singlecoder** [oasis-engine/create-oasis-app#9]
- 现在模版还是 0.6 的，建议更新到 0.8
- 创建工程的时候如果可以加一个引擎版本选择就更好了，默认最新版本

**Comment by gz65555** [comment]
后续和引擎版本保持一致吧，比如你要用 0.6 版本引擎。
安装 0.6 的 create-oasis-app 即可
```shell
npm init @oasis-engine/oasis-app@^0.6
```

**Comment by gz65555** [comment]
已经升级到 0.7，0.8 正式之后再升级
